### ISSUE TITLE
Localized string contains invalid token

### ISSUE THREAD

**Issue by guojiubo** [microsoft/localizationkit#11]
We have following strings that will trigger invalid token error, but the localized string seems reasonable to us, so what should we do in this case?

Origin string: "75 percent of original size"
Localized string: "75% delle dimensioni originali"

**Comment by dalemyers** [comment]
Fixed [here](https://github.com/microsoft/localizationkit/commit/f3fbc7244e0f62954fcea6bc5fdb56c79077f7ea) and released in 1.0.1
